# Generated by Django 4.1.1 on 2022-09-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_member_active_member_date_joined_specialitytags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to='projects.member'),
        ),
    ]
