# Generated by Django 4.1.1 on 2022-09-22 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_specialitytags_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.member'),
        ),
    ]
