# Generated by Django 4.1.1 on 2022-09-22 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_profileimage_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.member'),
        ),
    ]
