# Generated by Django 4.1.1 on 2022-09-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_profileimage_member'),
        ('projects', '0005_alter_profileimage_member'),
    ]

    operations = [
    ]
