# Generated by Django 4.1.1 on 2022-09-23 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_merge_20220923_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialitytags',
            name='member',
        ),
        migrations.RemoveField(
            model_name='specialitytags',
            name='speciality',
        ),
        migrations.AddField(
            model_name='specialitytags',
            name='name',
            field=models.CharField(choices=[('GIT/GITHUB', 'Git/Github'), ('SHELL', 'Shell'), ('EMACS', 'Emacs'), ('VI', 'Vi'), ('C', 'C'), ('PYTHON', 'Python')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='member',
            name='speciality',
        ),
        migrations.AddField(
            model_name='member',
            name='speciality',
            field=models.ManyToManyField(blank=True, to='projects.specialitytags'),
        ),
    ]
