# Generated by Django 4.1.1 on 2022-09-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_specialitytags_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialitytags',
            old_name='name',
            new_name='speciality',
        ),
    ]
