# Generated by Django 4.1.1 on 2022-09-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_name_specialitytags_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialitytags',
            name='speciality',
            field=models.CharField(choices=[('Git/Github', 'Git/Github'), ('Shell', 'Shell'), ('Emacs', 'Emacs'), ('VI', 'Vi'), ('C', 'C'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('Flask', 'Flask')], max_length=100),
        ),
    ]
