# Generated by Django 4.1.1 on 2022-10-05 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_member_options_topic_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['date_joined']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='subtopics',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
