# Generated by Django 4.1.1 on 2022-10-05 02:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_member_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topics',
        ),
        migrations.AddField(
            model_name='topic',
            name='topics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.specialitytags'),
            preserve_default=False,
        ),
    ]
