# Generated by Django 4.1.1 on 2022-10-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_topic_topics_topic_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='subtopics',
        ),
        migrations.AddField(
            model_name='topic',
            name='subtopics',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
