# Generated by Django 4.1.1 on 2022-10-05 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_quiz_subtopics_topic_subtopics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='topic',
            new_name='topics',
        ),
    ]
