# Generated by Django 4.1.1 on 2022-10-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_rename_topic_quiz_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subtopics',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
