# Generated by Django 4.1.1 on 2022-10-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_topic_subtopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
