# Generated by Django 4.1.1 on 2022-10-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_topic_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.topic')),
            ],
        ),
    ]
