# Generated by Django 4.1.1 on 2022-09-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_member_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='speciality',
            field=models.CharField(choices=[('GIT/GITHUB', 'Git/Github'), ('SHELL', 'Shell'), ('EMACS', 'Emacs'), ('VI', 'Vi'), ('C', 'C'), ('PYTHON', 'Python')], max_length=10),
        ),
    ]
